//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6MVC5010.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule6BuildingData
    {
        public int BuildingId { get; set; }
        public string SiteId { get; set; }
        public string TTSiteRef { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> PropertyNo { get; set; }
        public string BU { get; set; }
        public Nullable<int> GOR { get; set; }
        public string BuildingName { get; set; }
        public string BuildingAddress1 { get; set; }
        public string BuildingAddress2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string ContractId { get; set; }
        public string MajorOrMinor { get; set; }
        public Nullable<System.DateTime> ProposedVacantDate { get; set; }
        public string BuildingMaintenance { get; set; }
        public string BuildingManagement { get; set; }
        public string EnergyAndUtilitiesManagement { get; set; }
        public string LandscapeMaintenance { get; set; }
        public string ExternalCleaning { get; set; }
        public string WasteManagement { get; set; }
        public string CateringFacilitiesAndEquipment { get; set; }
        public string SecurityService { get; set; }
        public string InternalCleaning { get; set; }
        public string Porterage { get; set; }
        public string SecurityEquipment { get; set; }
        public string CustomerStewardingService { get; set; }
        public string CateringService { get; set; }
        public string EquipmentMaintenance { get; set; }
        public string CommercialRef { get; set; }
        public string CommercialRefExtra { get; set; }
        public string CommercialRefExtra2 { get; set; }
        public Nullable<System.DateTime> VOLogUpdate { get; set; }
        public string AegisSite { get; set; }
        public Nullable<System.DateTime> AEGISLiveDate { get; set; }
        public bool ServicesConfirmed { get; set; }
        public bool SCHED6SRVSREQD { get; set; }
        public string OriginalBaselineOperatingBand { get; set; }
        public string CurrentOperatingBand { get; set; }
        public string NormalWorkingHours { get; set; }
        public string PublicOpeningHours { get; set; }
    }
}
